services:
  app:
    build:
      context: .
      target: production
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:secret@mongo:27017/express-mongo-db-prod?authSource=admin"
      NODE_ENV: production
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: express-mongo-db-prod
      MONGO_LOG_LEVEL: error # Устанавливаем уровень логирования в error
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
